name: Run tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'firestore_size/**'
      - 'tests/**'
      - '.github/**' # temp
  push:
    branches:
      - master
    paths:
      - 'firestore_size/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          # if requirements or requirements_test changes, cache will be rebuilt
          key: ${{ hashFiles('**/requirements*.txt') }}
      - name: Install dependencies
        # reinstall requirements on cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - name: Run Test
        run: python3 setup.py pytest
